import threading
import queue
import logging

logger = logging.getLogger(__name__)

class IntermediateMemoryStore:
    """Stores the insights generated by the Fast Layer."""
    def __init__(self):
        self.insights = []

    def add_insight(self, insight: str):
        self.insights.append(insight)

    def get_all(self) -> str:
        return "\n".join(self.insights)

    def clear(self):
        self.insights = []


class RawTranscriptStore:
    """Stores all raw transcribed text from the live stream as a reliable fallback."""
    def __init__(self):
        self._lock = threading.Lock()
        self._text = ""

    def add(self, text: str):
        with self._lock:
            self._text += " " + text

    def get_all(self) -> str:
        with self._lock:
            return self._text.strip()

    def clear(self):
        with self._lock:
            self._text = ""


class ChunkQueueSystem:
    """
    Buffers streaming ASR text and asynchronously sends chunks to the Fast Layer
    (chunking_model) for rapid topic and action extraction.
    """
    def __init__(self, ollama_client, chunking_model: str, memory_store: IntermediateMemoryStore, raw_store: RawTranscriptStore):
        self.ollama_client = ollama_client
        self.chunking_model = chunking_model
        self.memory_store = memory_store
        self.raw_store = raw_store
        
        self.text_queue = queue.Queue()
        self.is_running = False
        self.worker_thread = None
        self.buffer = ""

    def start(self):
        self.is_running = True
        self.worker_thread = threading.Thread(target=self._process_queue, daemon=True)
        self.worker_thread.start()
        logger.info(f"Chunk Queue System started with Fast Layer model: {self.chunking_model}")

    def stop(self):
        """Stop the worker thread immediately. Discard pending MIC audio but preserve already-queued text in raw store."""
        self.is_running = False
        if self.worker_thread:
            self.worker_thread.join(timeout=2.0)
            
        # Drain pending queue items into raw store (already transcribed, just not yet analyzed)
        while not self.text_queue.empty():
            try:
                text = self.text_queue.get_nowait()
                self.raw_store.add(text)
                self.text_queue.task_done()
            except queue.Empty:
                break

        # Also flush the in-memory buffer into raw store
        if self.buffer.strip():
            self.raw_store.add(self.buffer.strip())
            self.buffer = ""

    def add_text(self, text: str):
        # Track all raw text immediately for the fallback store
        self.raw_store.add(text)
        self.text_queue.put(text)

    def _process_queue(self):
        while self.is_running:
            try:
                text = self.text_queue.get(timeout=1.0)
                self.buffer += text + " "
                
                # If we have a reasonable chunk (~150 words) process it via Fast Layer
                if len(self.buffer.split()) > 150:
                    chunk_to_process = self.buffer.strip()
                    self.buffer = ""
                    self._analyze_chunk(chunk_to_process)
                    
                self.text_queue.task_done()
            except queue.Empty:
                continue
            except Exception as e:
                logger.error(f"Error in Fast Layer: {e}")

    def _analyze_chunk(self, text: str):
        prompt = (
            "You are an expert meeting analyst. Analyze the following live meeting transcript chunk carefully.\n"
            "IMPORTANT: The transcript may be in English, Hindi, or Hinglish (a natural mix of Hindi and English words written in Roman/English script). "
            "You must understand all three and extract information from all of them.\n"
            "Extract ALL of the following that appear in the text:\n"
            "1. CONTEXT: What is being discussed overall in this section?\n"
            "2. KEY POINTS: Specific facts, proposals, arguments, or ideas raised.\n"
            "3. DECISIONS: Any decisions explicitly made or agreed upon.\n"
            "4. ACTION ITEMS: Specific tasks assigned to anyone (include person's name if mentioned).\n"
            "5. IMPORTANT NUMBERS/DATES: Any deadlines, figures, or dates mentioned.\n"
            "OUTPUT RULES: Be concise. Do NOT skip any important information. "
            "Write your output ONLY in clear professional English regardless of the input language.\n\n"
            f"Transcript Chunk:\n{text}"
        )
        
        try:
            insight = self.ollama_client._call_generate(
                model=self.chunking_model, 
                prompt=prompt, 
                word_limit=150
            )
            if insight:
                self.memory_store.add_insight(insight)
                logger.info(f"Fast Layer Insight extracted.")
        except Exception as e:
            logger.error(f"Fast Layer generation failed: {e}")

class StreamingMOMPipeline:
    def __init__(self, ollama_client, chunking_model: str, refinement_model: str):
        self.ollama_client = ollama_client
        self.chunking_model = chunking_model
        self.refinement_model = refinement_model
        
        self.memory_store = IntermediateMemoryStore()
        self.raw_store = RawTranscriptStore()
        self.chunk_queue = ChunkQueueSystem(self.ollama_client, self.chunking_model, self.memory_store, self.raw_store)
        
    def start(self):
        self.memory_store.clear()
        self.raw_store.clear()
        self.chunk_queue.start()
        
    def stop(self):
        self.chunk_queue.stop()
        
    def add_transcript_text(self, text: str):
        self.chunk_queue.add_text(text)
        
    def generate_final_mom(self, duration: str = None) -> str:
        """
        Generate MOM from insights if available, otherwise fall back to raw transcript.
        This guarantees a MOM is always generated as long as any speech was captured.
        """
        import datetime
        current_time = datetime.datetime.now().strftime("%B %d, %Y at %I:%M %p")
        duration_text = f"The actual duration of the meeting was {duration}. " if duration and duration != "N/A" else ""


        all_insights = self.memory_store.get_all()
        raw_transcript = self.raw_store.get_all()

        # Nothing at all was captured
        if not all_insights.strip() and not raw_transcript.strip():
            logger.info("No insights and no raw transcript. Skipping LLM call.")
            return "No meeting content was captured during this stream. Please ensure your microphone is working and try again."

        # Verify Ollama is running
        status = self.ollama_client.verify_connection()
        if not status['connected']:
            return f"=== ERROR ===\n\n{status['error']}"

        # --- PATH 1: Use insights (long stream, Fast Layer had time to process) ---
        if all_insights.strip():
            num_chunks = len(self.memory_store.insights)
            logger.info(f"Generating final MOM from {num_chunks} Fast Layer insight(s)...")
            prompt = (
                "You are an expert professional secretary with years of corporate meeting documentation experience.\n"
                f"A live meeting concluded on {current_time}. {duration_text}It produced {num_chunks} summarized chunk(s) of discussion.\n\n"
                "IMPORTANT: The original meeting may have been conducted in English, Hindi, or Hinglish (a mix of Hindi and English). "
                "The chunk summaries below may contain Hinglish words or phrases. "
                "Your final MOM MUST be written entirely in clear, formal, professional English. Translate any Hindi or Hinglish content into English.\n\n"
                "Your task is to synthesize ALL the chunk summaries below into ONE comprehensive, well-structured, and professional Minutes of Meeting (MOM).\n\n"
                "STRICT RULES:\n"
                "- Every piece of information from the summaries MUST appear in the final MOM. Do NOT omit any detail.\n"
                "- Do NOT repeat the same point multiple times.\n"
                "- Group related points together under the correct heading.\n"
                "- Action items MUST include the person responsible (if known) and deadline (if mentioned).\n"
                "- Write in clear, formal, professional English only. Use bullet points for readability.\n\n"
                "Use EXACTLY these headings (all must be present):\n"
                "## Date and Time\n"
                "## Actual Duration\n"
                "## Attendees (if mentioned, otherwise write: Not recorded)\n"
                "## Topics Discussed\n"
                "## Key Discussion Points\n"
                "## Decisions Made\n"
                "## Action Items\n"
                "## Next Steps (if mentioned, otherwise write: None specified)\n\n"
                f"=== CHUNK SUMMARIES ===\n{all_insights}\n=== END OF SUMMARIES ==="
            )

        # --- PATH 2: Fallback — use raw transcript directly (short stream, < 150 words, or stop pressed early) ---
        else:
            logger.info("No Fast Layer insights found. Falling back to direct raw transcript MOM generation...")
            prompt = (
                "You are an expert professional secretary with years of corporate meeting documentation experience.\n"
                f"A live meeting concluded on {current_time}. {duration_text}\n\n"
                "IMPORTANT: The transcript may be in English, Hindi, or Hinglish (a mix of Hindi and English). "
                "Your final MOM MUST be written entirely in clear, formal, professional English. Translate any Hindi or Hinglish content into English.\n\n"
                "Generate a comprehensive, well-structured Minutes of Meeting (MOM) from the following raw meeting transcript.\n\n"
                "STRICT RULES:\n"
                "- Every piece of information from the transcript MUST appear in the final MOM. Do NOT omit any detail.\n"
                "- Do NOT repeat the same point multiple times.\n"
                "- Write in clear, formal, professional English only. Use bullet points for readability.\n\n"
                "Use EXACTLY these headings (all must be present):\n"
                "## Date and Time\n"
                "## Actual Duration\n"
                "## Attendees (if mentioned, otherwise write: Not recorded)\n"
                "## Topics Discussed\n"
                "## Key Discussion Points\n"
                "## Decisions Made\n"
                "## Action Items\n"
                "## Next Steps (if mentioned, otherwise write: None specified)\n\n"
                f"=== RAW TRANSCRIPT ===\n{raw_transcript}\n=== END OF TRANSCRIPT ==="
            )

        try:
            final_mom = self.ollama_client._call_generate(
                model=self.refinement_model,
                prompt=prompt
            )
            return final_mom
        except Exception as e:
            logger.error(f"Error generating final MOM: {e}")
            return f"=== ERROR ===\n\nFailed to generate MOM: {str(e)}\nPlease ensure Ollama is running."
