#!/bin/bash

echo ""
echo " ================================================================"
echo "  MOM GENERATOR - AUTOMATED SETUP (macOS)"
echo "  AI-Powered Minutes of Meeting Application"
echo " ================================================================"
echo ""
echo "  This script installs EVERYTHING needed to run MOM Generator."
echo "  It may take 10-20 minutes on first run (downloading AI models)."
echo ""
read -p "  Press [Enter] to continue..."

# Get absolute path of the project root
INSTALL_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$(dirname "$(dirname "$INSTALL_DIR")")"
cd "$ROOT_DIR" || exit 1

# ================================================================
# STEP 1: Check Python
# ================================================================
echo ""
echo " [STEP 1/5]  Checking Python..."
if command -v python3 &> /dev/null; then
    echo "  Found: $(python3 --version)"
else
    echo "  [ERROR] Python 3 not found."
    echo "  Please install Python 3 using Homebrew (brew install python) or from python.org."
    exit 1
fi

# ================================================================
# STEP 2: Create Virtual Environment and Install Packages
# ================================================================
echo ""
echo " [STEP 2/5]  Setting up Python environment and packages..."
echo " (This downloads AI libraries - may take 5-10 minutes)"
echo ""

# We use a venv on macOS to avoid system python conflicts
if [ ! -d "venv" ]; then
    python3 -m venv venv
fi
source venv/bin/activate

export HF_HUB_DISABLE_SYMLINKS=1
export HF_HUB_DISABLE_SYMLINKS_WARNING=1

pip install --upgrade pip --quiet
pip install -r "$INSTALL_DIR/requirements.txt"
if [ $? -ne 0 ]; then
    echo ""
    echo " [ERROR] Failed to install Python packages."
    echo " Check your internet connection and try again."
    exit 1
fi
echo ""
echo " All Python packages installed!"

# ================================================================
# STEP 3: Check / Install Ollama
# ================================================================
echo ""
echo " [STEP 3/5]  Checking Ollama (Local AI engine)..."
if command -v ollama &> /dev/null; then
    echo "  Found: $(ollama --version)"
else
    echo "  Ollama not found. Attempting automatic install..."
    curl -fsSL https://ollama.com/install.sh | sh
    if [ $? -ne 0 ]; then
        echo ""
        echo " ================================================================"
        echo "  [ACTION REQUIRED] Could not auto-install Ollama."
        echo ""
        echo "  Please download and install Ollama manually for Mac:"
        echo "  https://ollama.com/download"
        echo ""
        echo "  After installing, run setup.sh again."
        echo " ================================================================"
        exit 1
    fi
    echo "  Ollama installed successfully!"
    sleep 3
fi

# ================================================================
# STEP 4: Pull AI Models via Ollama
# ================================================================
echo ""
echo " [STEP 4/5]  Downloading AI models..."
echo ""
echo " Starting Ollama service..."
# Start ollama in background
OLLAMA_HOST=127.0.0.1 ollama serve > /dev/null 2>&1 &
OLLAMA_PID=$!
sleep 4

echo " Waiting for Ollama service..."
while ! curl -s http://127.0.0.1:11434/api/tags > /dev/null; do
    sleep 2
done
echo " Ollama service is ready."
echo ""

echo " Downloading qwen2.5:1.5b  (Chunking model  - ~1.0 GB)..."
ollama pull qwen2.5:1.5b
if [ $? -ne 0 ]; then echo " [WARNING] qwen2.5:1.5b download failed."; fi

echo ""
echo " Downloading qwen2.5:7b  (Refinement model - ~4.7 GB)..."
ollama pull qwen2.5:7b
if [ $? -ne 0 ]; then echo " [WARNING] qwen2.5:7b download failed."; fi

echo ""
echo " AI models ready!"

# ================================================================
# STEP 5: Create .env config
# ================================================================
echo ""
echo " [STEP 5/5]  Creating configuration..."
cat << EOF > "$ROOT_DIR/.env"
# MOM Generator Environment Config - auto-generated by setup.sh
HF_HUB_DISABLE_SYMLINKS=1
HF_HUB_DISABLE_SYMLINKS_WARNING=1
OLLAMA_URL=http://127.0.0.1:11434
EOF
echo " Configuration file created."

# ================================================================
# SETUP COMPLETE
# ================================================================
echo ""
echo " ================================================================"
echo "  SETUP COMPLETE!"
echo " ================================================================"
echo ""
echo "  Everything is installed and ready to use!"
echo ""
echo "  HOW TO USE THE APP:"
echo "    1. Run  bash START_APP/START_APP.sh  (from the main folder)"
echo "    2. Your browser will open automatically"
echo "    3. Use the app at http://127.0.0.1:5001"
echo ""
echo "  You only need to run setup.sh ONCE."
echo "  For all future launches, just use START_APP.sh"
echo ""

# Cleanup background ollama serve just to be safe, START_APP.sh will handle it
kill $OLLAMA_PID 2>/dev/null

read -p " Press [Enter] to exit setup..."
